{:user {:plugins [
                  #_[lein-cljfmt "RELEASE"]
                  #_[lein-hiera  "RELEASE"]
                  #_[lein-heroku "RELEASE"]
                  #_[lein-pprint "1.2.0"]
                  #_[quickie "RELEASE"]
                  #_[lein-try "RELEASE"]
                  #_[lein-ring "RELEASE"]
                  #_[lein-plz "RELEASE"]
                  #_[lein-cloverage "RELEASE"]]
        :dependencies [[cljfmt "RELEASE"]
                       [cider/cider-nrepl "RELEASE"]
                       [binaryage/devtools "RELEASE"]
                       [jonase/eastwood "RELEASE"]
                       [com.cemerick/piggieback "RELEASE"]
                       [slamhound "RELEASE"]
                       [org.clojure/tools.nrepl "RELEASE"]]}}
